# Generated by Django 4.1.7 on 2023-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola_mundo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('nacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tipo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_producto',
            new_name='precio_unidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='preciounidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_Producto',
            field=models.CharField(default='sin nombre', max_length=100),
        ),
    ]
