# Generated by Django 4.1.7 on 2023-04-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola_mundo', '0002_persona_delete_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_Producto',
            field=models.CharField(max_length=100),
        ),
    ]
