# Generated by Django 4.1.7 on 2023-04-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola_mundo', '0003_alter_producto_nombre_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
        migrations.AddField(
            model_name='venta',
            name='apellidocomprador',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='nombrecomprador',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='numerofactura',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
