# Generated by Django 4.1.7 on 2023-04-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hola_mundo', '0004_remove_venta_estado_venta_apellidocomprador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='apellidocomprador',
            new_name='apellido_comprador',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='nombrecomprador',
            new_name='nombre_comprador',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='numerofactura',
            new_name='numero_factura',
        ),
    ]
