# Generated by Django 4.1.7 on 2023-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondMarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='carousel_caption_title',
            new_name='Nombre_Producto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='carousel_caption_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heading',
        ),
        migrations.AddField(
            model_name='post',
            name='Precio_Producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
