# Generated by Django 4.1.7 on 2023-04-22 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SecondMarket', '0002_rename_carousel_caption_title_post_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='DueñoPost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DueñoPost', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
