# Generated by Django 4.1.7 on 2023-04-22 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SecondMarket', '0007_alter_post_imagen_alter_profile_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
